FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libffi-dev \
        libssl-dev \
        libpcap-dev \
        python3-dev \
    && pip install --no-cache-dir opencanary==0.9.3 \
    && apt-get purge -y --auto-remove build-essential libffi-dev libssl-dev python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/log/opencanary

COPY config/opencanary/opencanary.conf /root/.opencanary.conf

CMD ["opencanaryd", "--start", "--nodaemon"]
